### ISSUE TITLE
delete repos.json

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/sloth#730]
With both `repos.json` and DRIFT responsible for tracking GitHub repositories, it means there are two sources of truth.  We should make DRIFT the single source of truth.  Let's use this issue to track down all usages of `repos.json` that need to be rationalized.
- [x] [autosynth](https://github.com/googleapis/synthtool/issues/645)
- [x] [google-cloud-node](https://github.com/googleapis/google-cloud-node/issues/3012)
- [x] [github-repo-automation](https://github.com/googleapis/github-repo-automation/issues/417)
- [x] [repo-automation-bots](https://github.com/googleapis/repo-automation-bots/issues/623)
- [ ] This repository!

**Comment by meredithslota** [comment]
Re-assigning to @bcoe to hang on to for now as we decide how to move forward.
